# Generated by Django 5.1.5 on 2025-01-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
